### PR TITLE
Simple fixes of last pr #95

### PR DESCRIPTION
**Pull request by emecdelam**
Fixed wrong int used for spoiler detection (2 instead of 1)
also added the spoiler after the ` formatting in the perform response

Note : this has not yet been tested changes where made using github.dev trial are expected soon even tho everything should work in *theory*

### CODE REVIEW

**Comment by Hokkaydo** [comment]
Hey, 
Have you been able to test your changes since then ?

**Comment by emecdelam** [comment]
Somehow I'm not able to pass three arguments when using the command it's still stuck with two, it seems like the API won't update it. Any suggestion on how to fix this?

**Comment by Hokkaydo** [comment]
There is a "/refreshcommands" command to refresh the bot's commands list. I would have liked to update them at each module enabling/disabling or at the bot starting but there's a strong API limit which denies too much requests about updating command lists

**Comment by emecdelam** [comment]
image


image


it should be working, sorry for the bugs from last pr, I indeed had trouble refreshing from the API

**Pull request merged**
